name: Main Branch CI example

on:
  push:
    branches: main

jobs:
  test_on_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout zenoh
        uses: actions/checkout@v4
        with:
          repository: eclipse-zenoh/zenoh
          path: zenoh
          ref: '0.11.0'
      - name: test Zenoh
        run: |
          set -x
          sudo chown -R 1000 zenoh
          time docker run \
            -v $(realpath zenoh):/src \
            -v $(realpath scripts):/scripts \
            -e "CI_COMMAND=/scripts/setup_host.sh && /scripts/test-zenoh.sh" \
            ghcr.io/flba-eb/ebcl_cicd_template:main
