name: Main Branch CI

# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        id: ebcl_image
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: eclipse-zenoh/zenoh
          path: zenoh
          ref: '0.11.0'
      - name: test Zenoh
        run: |
          set -x
          echo "Using image ID: ${{ steps.ebcl_image.outputs.imageid }}"
          echo "Local host: $(uname -a)"
          docker run -v $(realpath zenoh):/src ${{ steps.ebcl_image.outputs.imageid }} ./test-zenoh.sh
